# Generated by Django 6.0 on 2025-12-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-Veg'), ('egg', 'Egg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
    ]
